[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

# upgrade yazi plugins
upgrade:
    mise x aqua:sxyazi/yazi -- ya pkg upgrade

# install yazi plugins
install:
    mise x aqua:sxyazi/yazi -- ya pkg install
