[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

# upgrade yazi plugins
upgrade:
    mise x yazi -- ya pack -u

# install yazi plugins
install:
    mise x yazi -- ya pack -i
