[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

githubusercontent := "https://raw.githubusercontent.com"
plugin_dir := ".oh-my-zsh/custom/plugins"

# upgrade zsh plugins
upgrade:
    @echo -n "Updating github-cli completions..."
    @mkdir -p {{ plugin_dir }}/gh && \
        mise x github-cli -- gh completion -s zsh > {{ plugin_dir }}/gh/_gh
    @echo "DONE"

    @echo -n "Updating just completions..."
    @mkdir -p {{ plugin_dir }}/just && \
        mise x just -- just --completions zsh > {{ plugin_dir }}/just/_just
    @echo "DONE"

    @echo -n "Updating restic completions..."
    @mkdir -p {{ plugin_dir }}/restic && \
        mise x restic -- restic -q generate --zsh-completion {{ plugin_dir }}/restic/_restic
    @echo "DONE"

    @echo -n "Updating hcloud completions..."
    @mkdir -p {{ plugin_dir }}/hcloud && \
        mise x hcloud -- hcloud completion zsh > {{ plugin_dir }}/hcloud/_hcloud
    @echo "DONE"

    @echo -n "Updating ruff completions..."
    @mkdir -p {{ plugin_dir }}/ruff && \
        mise x ruff -- ruff generate-shell-completion zsh > {{ plugin_dir }}/ruff/_ruff
    @echo "DONE"

    @echo -n "Updating bitwarden-secrets-manager completions..."
    @mkdir -p {{ plugin_dir }}/bws && \
        mise x bitwarden-secrets-manager -- bws completions zsh > {{ plugin_dir }}/bws/_bws
    @echo "DONE"

    @echo -n "Updating ripgrep completions..."
    @mkdir -p {{ plugin_dir }}/rg && \
        mise x ripgrep -- rg --generate complete-zsh > {{ plugin_dir }}/rg/_rg
    @echo "DONE"

    @echo -n "Updating mise completions..."
    @mkdir -p {{ plugin_dir }}/mise && \
        mise completion zsh > {{ plugin_dir }}/mise/_mise
    @echo "DONE"

    @echo -n "Updating tldr completions..."
    @mkdir -p {{ plugin_dir }}/tldr && \
        curl -s {{ githubusercontent }}/tldr-pages/tlrc/main/completions/_tldr \
            --output {{ plugin_dir }}/tldr/_tldr
    @echo "DONE"

    @echo -n "Updating fd completions..."
    @mkdir -p {{ plugin_dir }}/fd && \
        curl -s {{ githubusercontent }}/sharkdp/fd/refs/heads/master/contrib/completion/_fd \
            --output {{ plugin_dir }}/fd/_fd
    @git submodule update --init --recursive
    @echo "DONE"

    @echo -n "Updating zsh-completions plugin..."
    @git -C {{ plugin_dir }}/zsh-completions pull -q
    @echo "DONE"

    @echo -n "Updating zsh-syntax-highlighting plugin..."
    @git -C {{ plugin_dir }}/zsh-syntax-highlighting pull -q
    @echo "DONE"

    @{{ env("ZSH") }}/tools/upgrade.sh -v minimal
    @echo "DONE"
