[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

githubusercontent := "https://raw.githubusercontent.com"
plugin_dir := join(env("ZSH_CUSTOM", "~/.oh-my-zsh/custom"), "plugins")
tool_dir := join(env("ZSH", "~/.oh-my-zsh"), "tools")

# upgrade zsh plugins
upgrade:
    @echo -n "Updating github-cli completions..."
    @mkdir -p {{ plugin_dir }}/gh && \
        mise x github-cli -- gh completion -s zsh > {{ plugin_dir }}/gh/_gh
    @echo "DONE"

    @echo -n "Updating just completions..."
    @mkdir -p {{ plugin_dir }}/just && \
        mise x just -- just --completions zsh > {{ plugin_dir }}/just/_just
    @echo "DONE"

    @echo -n "Updating jj completions..."
    @mkdir -p {{ plugin_dir }}/jj && \
        mise x jj -- jj util completion zsh > {{ plugin_dir }}/jj/_jj
    @echo "DONE"

    @echo -n "Updating restic completions..."
    @mkdir -p {{ plugin_dir }}/restic && \
        mise x restic -- restic -q generate --zsh-completion {{ plugin_dir }}/restic/_restic
    @echo "DONE"

    @echo -n "Updating hcloud completions..."
    @mkdir -p {{ plugin_dir }}/hcloud && \
        mise x hcloud -- hcloud completion zsh > {{ plugin_dir }}/hcloud/_hcloud
    @echo "DONE"

    @echo -n "Updating ruff completions..."
    @mkdir -p {{ plugin_dir }}/ruff && \
        mise x ruff -- ruff generate-shell-completion zsh > {{ plugin_dir }}/ruff/_ruff
    @echo "DONE"

    @echo -n "Updating vectorcode completions..."
    @mkdir -p {{ plugin_dir }}/vectorcode && \
        mise x "pipx:vectorcode" -- vectorcode --print-completion zsh > {{ plugin_dir }}/vectorcode/_vectorcode
    @echo "DONE"

    @echo -n "Updating bitwarden-secrets-manager completions..."
    @mkdir -p {{ plugin_dir }}/bws && \
        mise x "github:bitwarden/sdk-sm@bws-v1.0.0" -- bws completions zsh > {{ plugin_dir }}/bws/_bws
    @echo "DONE"

    @echo -n "Updating ripgrep completions..."
    @mkdir -p {{ plugin_dir }}/rg && \
        mise x ripgrep -- rg --generate complete-zsh > {{ plugin_dir }}/rg/_rg
    @echo "DONE"

    @echo -n "Updating bat completions..."
    @mkdir -p {{ plugin_dir }}/bat && \
        mise x bat -- bat --completion zsh > {{ plugin_dir }}/bat/_bat
    @echo "DONE"

    @echo -n "Updating xh completions..."
    @mkdir -p {{ plugin_dir }}/xh && \
        mise x xh -- xh --generate complete-zsh > {{ plugin_dir }}/xh/_xh
    @echo "DONE"

    @echo -n "Updating dive completions..."
    @mkdir -p {{ plugin_dir }}/dive && \
        mise x dive -- dive completion zsh > {{ plugin_dir }}/dive/_dive
    @echo "DONE"

    @echo -n "Updating mise completions..."
    @mkdir -p {{ plugin_dir }}/mise && \
        mise completion zsh > {{ plugin_dir }}/mise/_mise
    @echo "DONE"

    @echo -n "Updating tldr completions..."
    @mkdir -p {{ plugin_dir }}/tldr && \
        curl -s {{ githubusercontent }}/tldr-pages/tlrc/main/completions/_tldr \
            --output {{ plugin_dir }}/tldr/_tldr
    @echo "DONE"

    @echo -n "Updating fd completions..."
    @mkdir -p {{ plugin_dir }}/fd && \
        curl -s {{ githubusercontent }}/sharkdp/fd/refs/heads/master/contrib/completion/_fd \
            --output {{ plugin_dir }}/fd/_fd
    @echo "DONE"

    @echo -n "Updating dust completions..."
    @mkdir -p {{ plugin_dir }}/dust && \
        curl -s {{ githubusercontent }}/bootandy/dust/refs/heads/master/completions/_dust \
            --output {{ plugin_dir }}/dust/_dust
    @echo "DONE"

    @echo -n "Updating dbt completions..."
    @mkdir -p {{ plugin_dir }}/dbt && \
        curl -s {{ githubusercontent }}/dbt-labs/dbt-completion.bash/refs/heads/master/_dbt \
            --output {{ plugin_dir }}/dbt/_dbt
    @echo "DONE"

    @git submodule update --init --recursive

    @echo -n "Updating zsh-completions plugin..."
    @git -C {{ plugin_dir }}/zsh-completions pull -q
    @echo "DONE"

    @echo -n "Updating zsh-syntax-highlighting plugin..."
    @git -C {{ plugin_dir }}/zsh-syntax-highlighting pull -q
    @echo "DONE"

    @{{ tool_dir }}/upgrade.sh -v minimal
    @echo "DONE"
