#!/bin/sh
# elvis: dictcc	-- Search for translations (www.dict.cc))
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search dict.cc (www.dict.cc) for german-english translations.
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.dict.cc/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.dict.cc/?s=${escaped_args}"
fi
