#!/usr/bin/env zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERMINAL="/usr/local/bin/st"
export MANPATH="/usr/local/texlive/2017/texmf-dist/doc/man:$MANPATH"
export INFOPATH="/usr/local/texlive/2017/texmf-dist/doc/info:$INFOPATH"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.fzf/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"
export GPG_TTY=$(tty)
export SDCV_PAGER="less"
export BROWSER="firefox"
export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/projects"
export PYTHONBREAKPOINT="ipdb.set_trace"
