#!/bin/bash

# Change keyboard layout to Colemak.
setxkbmap -layout us -variant colemak

# Treat Control_L as Escape when it is pressed and released on its own,
xcape

# Increase key repeat rate.
xset r rate 200 50

# Map the menu button to right super.
xmodmap -e 'keycode 135 = Super_R'
