hotkeys:
  profile: {}
  settings: []
  copy:
    - - Ctrl-Shift-C
  home: []
  end: []
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  zoom-in:
    - - Ctrl-Alt-=
  zoom-out:
    - - Ctrl-Alt--
  shell: {}
  reset-zoom:
    - - Ctrl-Alt-0
  new-tab: []
  ctrl-c: []
  search: []
  ssh:
    - - Alt-T
  new-window:
    - - Alt-N
  toggle-window: []
  toggle-fullscreen:
    - - Alt-Enter
  rename-tab: []
  close-tab: []
  next-tab: []
  previous-tab: []
  tab-1:
    - - Alt-1
  tab-2:
    - - Alt-2
  tab-3:
    - - Alt-3
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  split-right: []
  split-bottom: []
  pane-maximize: []
  pane-nav-up: []
  pane-nav-down: []
  pane-nav-left: []
  pane-nav-right: []
terminal:
  colorScheme:
    name: Gruvbox Dark
    foreground: "#ebdbb2"
    background: "#282828"
    cursor: "#bbbbbb"
    colors:
      - "#161819"
      - "#f73028"
      - "#aab01e"
      - "#f7b125"
      - "#719586"
      - "#c77089"
      - "#7db669"
      - "#faefbb"
      - "#7f7061"
      - "#be0f17"
      - "#868715"
      - "#cc881a"
      - "#377375"
      - "#a04b73"
      - "#578e57"
      - "#e6d4a3"
  font: Hack NF Regular
  background: colorScheme
  environment: {}
  profile: powershell
  rightClick: menu
  scrollOnInput: false
  ligatures: false
  frontend: hterm
  cursorBlink: false
  customColorSchemes:
    - name: Gruvbox Dark
      foreground: "#ebdbb2"
      background: "#282828"
      cursor: "#bbbbbb"
      colors:
        - "#161819"
        - "#f73028"
        - "#aab01e"
        - "#f7b125"
        - "#719586"
        - "#c77089"
        - "#7db669"
        - "#faefbb"
        - "#7f7061"
        - "#be0f17"
        - "#868715"
        - "#cc881a"
        - "#377375"
        - "#a04b73"
        - "#578e57"
        - "#e6d4a3"
  copyOnSelect: true
  pasteOnMiddleClick: false
  bracketedPaste: true
  fontSize: 16
appearance:
  vibrancy: false
  frame: thin
  theme: Compact
  tabsLocation: top
  opacity: 0.97
  vibrancyType: fluent
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
serial: {}
enableAutomaticUpdates: false
