[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

# upgrade mise tools
upgrade:
    mise up --bump --interactive --exclude lua

# install mise tools
install *args:
    mise i {{ args }}
