[private]
default:
    @just --justfile {{ source_file() }} --list --unsorted

build:
    docker build \
        --tag workmux-sandbox \
        --secret id=GITHUB_TOKEN \
        {{ justfile_dir() }}/workmux
