---
gui:
  returnImmediately: true
customCommands:
  containers:
    - name: 'human logs'
      attach: true
      shell: true
      command: 'docker logs --follow --tail 300 {{ .Container.Name }} 2>&1 | hl -P
        --allow-prefix'
  services:
    - name: 'human logs'
      attach: true
      shell: true
      command: '{{ .DockerCompose }} logs --follow --tail 300 {{ .Service.Name }}
        2>&1 | hl -P --allow-prefix'
